import * as fs from 'fs';
import * as path from 'path';
import * as ErrorDetails from '../src/gen/googleapis/google/rpc/error_details_pb.js';



export default function generateIndex(indexPath: string, protoPath: string): void {
    const dirname = path.dirname(indexPath)
    if (!fs.existsSync(dirname)) {
        fs.mkdirSync(dirname);
    }

    let index = 0;
    while(dirname[index] === protoPath[index]) {
        index++;
    }

    const remainingPath = dirname.substr(index);
    const relativePath = protoPath.substr(index).replace(/^\//, '');
    const subdirCount = (remainingPath.match(/\//g) || []).length;
    const prefix = './' + '../'.repeat(subdirCount);

    const errDetailClasses = Object.keys(ErrorDetails).filter(key => key !== "default");

    const Index = `
// This file is automatically generated
export { Status } from "./status";
export {
  ${errDetailClasses.join(",\n  ")}
} from "${prefix}${relativePath}/error_details_pb";`;

    fs.writeFileSync(indexPath, Index);
}
