import * as fs from 'fs';
import * as ErrorDetails from '../src/gen/googleapis/google/rpc/error_details_pb';



export default function generateDetail(typesPath: string, protoPath: string): void {
    if (!fs.existsSync(typesPath)) {
        fs.mkdirSync(typesPath);
    }

    let index = 0;
    while(typesPath[index] === protoPath[index]) {
        index++;
    }

    const remainingPath = typesPath.substr(index);
    const relativePath = protoPath.substr(index).replace(/^\//, '');
    const subdirCount = (remainingPath.match(/\//g) || []).length;
    const prefix = './' + '../'.repeat(subdirCount);

    let Detail = `
// This file is automatically generated
import * as ErrorDetails from "${prefix}${relativePath}/error_details_pb";

export type Detail =
`;

    Object.keys(ErrorDetails).forEach(key => {
        if (key === 'default') {
            return;
        }
        Detail +=`    | ErrorDetails.${key}
`;
    });

    Detail += ';';

    fs.writeFileSync(`${typesPath}/Detail.d.ts`, Detail);
}
