
// This file is automatically generated
export { Status } from "./status";
export {
  BadRequest,
  DebugInfo,
  ErrorInfo,
  Help,
  LocalizedMessage,
  PreconditionFailure,
  QuotaFailure,
  RequestInfo,
  ResourceInfo,
  RetryInfo
} from "./gen/googleapis/google/rpc/error_details_pb";